services:
  behavior-detection:
    build:
      args:
        BUILD_TYPE: gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
